# generated by datamodel-codegen:
#   filename:  harness.openapi.yaml

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict


class JsonObject(TypedDict):
    pass


RuntimeMethod: TypeAlias = Literal[
    'agent/create',
    'agent/update',
    'agent/delete',
    'agent/applyTemplate',
    'skills/list',
    'skills/install',
    'skills/update',
    'skills/uninstall',
    'models/list',
    'cron/list',
    'cron/status',
    'cron/add',
    'cron/update',
    'cron/remove',
    'cron/run',
    'cron/runs',
    'mcp/list',
    'mcp/prepare',
    'mcp/set',
    'mcp/unset',
    'session/set_mode',
    'session/set_model',
    'session/clear',
    'session/cancel',
    'session/prompt',
    'canvas/toggle',
    'canvas/clear',
    'canvas/reference',
    'canvas/dimensions',
]


class RuntimeDeliveriesReadRequest(TypedDict):
    schemaVersion: Literal[1]
    maxCount: int
    blockMs: int


class RuntimeDeliveryIdsRequest(TypedDict):
    schemaVersion: Literal[1]
    deliveryIds: list[str]


class RuntimeOperationAppendRequest(TypedDict):
    schemaVersion: Literal[1]
    type: str
    payload: Any


class RuntimeConversationSyncRequest(TypedDict):
    schemaVersion: Literal[1]
    operationId: str
    runtimeSessionId: str
    runtimeSessionKey: NotRequired[str]
    title: NotRequired[str]


class RuntimeMessagePatch(TypedDict):
    body: NotRequired[str]
    body_append: NotRequired[str]
    body_from: NotRequired[int]
    parts: NotRequired[list[JsonObject]]
    state: NotRequired[str]
    stop_reason: NotRequired[str]


class TerminalAgentAuthFrame(TypedDict):
    type: Literal['agent_auth']
    instance_id: str
    service: Literal['terminal']
    public_key: str
    timestamp: int
    nonce: str
    signature: str
    runtimeLeaseCredential: str
    handlerIdentity: str
    runtimeEpoch: str
    leaseId: str


class CanvasRelayConnect(TypedDict):
    path: Literal['/ws/agent']
    agentIdQuery: NotRequired[str]
    tokenQuery: NotRequired[str]
